import Head from "next/head"
import { useContext } from "react";
import { GlobalContext } from "../../../context/GlobalContext";
import { ButtonLoader } from "../../../components/ButtonLoader";
import { SearchBar } from "../../../components/SearchBar";
import { documentToBlob } from "../../../helpers/fileReader";
import { AdminHeader } from "../../../components/AdminHeader";
import { SideBar } from "../../../components/SideBar";
import { useRouter } from "next/router";

const Product = () => {
    const router = useRouter();
    const { product: {
        handleState,
        msg,
        loading,
        products
    } } = useContext(GlobalContext);

    // console.log(products);

    return <div className="add-product flex">
        <Head>
            <title>UNI-STORE | Add Product</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <SideBar />

        <div className="main-component">
            <AdminHeader />
            <main>
                <section className="flex col">
                        <button onClick={() => router.push("/admin/orders")} className="btn">Orders</button>
                         <div className="space-2"></div>           
                    <div className="flex justify-between">
                        <button onClick={() => router.push("/admin/products/add-product")} className="btn">Add New</button>
                        <SearchBar />
                    </div>
                </section>
                <div className="space-1"></div>
                <section>
                    <h1>Products</h1>
                    <div className="flex col">
                        {products?.map((items, i) => {
                            return <div className="product-bar" key={i}>

                                <img src={items.image} />
                                <div className="space-1"></div>

                                <div>
                                    <p>{items.name} | {items.category}</p>
                                    <small>{items.description}</small>
                                    <div className="flex">
                                    <h1 className="flex">${items.regularPrice}</h1>
                                        <div className="space-2"></div>
                                    <del>${items.salePrice}</del>
                                    </div>
                                    
                                    <div className="flex">
                                        <button onClick={() => router.push(`/admin/products/edit-product/${items._id}`)}>Edit</button>
                                        <div className="space-2"></div>
                                        <button>Delete</button>
                                    </div>

                                </div>

                            </div>
                        })}
                    </div>

                </section>
            </main>
        </div>


    </div>
}

export default Product;
