import Head from "next/head";
import { useContext, useState } from "react";
import { GlobalContext } from "../../context/GlobalContext";
import { AdminHeader } from "../../components/AdminHeader";
import { SideBar } from "../../components/SideBar";
import { useRouter } from "next/router";

const Admin = () => {
  const router = useRouter();
  const {} = useContext(GlobalContext);
  const [sidebar, setSideBar] = useState(false);

  // console.log(Admins);

  return (
    <div className="add-Admin flex">
      <Head>
        <title>UNI-STORE | Add Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SideBar closeSideBar={() => setSideBar(false)} toggle={sidebar} />

      <div className="main-component">
        <AdminHeader toggleSideBar={() => setSideBar(true)} />
        <main>
          <section className="flex col"></section>
        </main>
      </div>
    </div>
  );
};

export default Admin;
