import Head from "next/head";
import Image from "next/image";
import { HomeHeader } from "../components/HomeHeader";
import HeroImage from "../assets/img/about-1.png";
import { HomeFooter } from "../components/HomeFooter";
import { CustomHero } from "../components/CustomHero";

export default function About() {
  return (
    <div className="landingpage">
      <Head>
        <title>UNI-STORE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeHeader />
      <CustomHero
        children={
          <div>
            <h1>About us</h1>
          </div>
        }
      />
      <div className="space-1"></div>
      <section className="about">
        <div className="center heading">
          <h1>About us</h1>
          <p>
            we sell many categories & varieties of products - shoes, books,
            eBooks, cloths, wears, electronics & others
          </p>
          <small>grab your's now</small>
          <div className="space-1"></div>

          <a href="#">See more</a>
        </div>

        <div className="flex justify-between text-left">
          <div className="flex col text-left">
            <h2>Who we are?</h2>

            <p className="text-left">
              connecting you with quality products like books, shoes, cloths and
              other innovative products in the market system around the world.
            </p>
            <div className="space-1"></div>

            <li>Best Seller Award</li>
            <li>Best Author Award</li>
            <li>Best Promotion Award</li>
          </div>

          <div className="space-1"></div>

          <Image src={HeroImage} />
        </div>
      </section>

      <HomeFooter />
    </div>
  );
}
