import Head from "next/head";
import Image from "next/image";
import { Hero } from "../components/Hero";
import { HomeHeader } from "../components/HomeHeader";
import HeroImage from "../assets/img/hero-1.jpg";

export default function Home() {
  return (
    <div className="landingpage">
      <Head>
        <title>UNI-STORE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeHeader />
      <Hero />
      <div className="space-1"></div>
      <section className="about">
        <h1>About us</h1>

        <div className="space-1"></div>

        <div className="flex justify-between text-left">
          
          <div>
            <p className="">
              <h2>Who we are?</h2>
              There are many variations of passages of Lorem Ipsum means
              available, but the majority have suffered alteration in some form,
              by inject humour, or randomised words which don't look even
              slightly from the end of believable. There are many variations of
              passages of Lorem Ipsum means available, but the majority have
              suffered alteration in some form, by inject humour, or randomised
              words which don't look even slightly from the end of believable.
              There are many variations of passages of Lorem Ipsum means
              available, but the majority have suffered alteration in some form,
              by inject humour, or randomised words which don't look even
              slightly from the end of believable.
            </p>
            <ul>
              <li>Best Seller Award</li>
              <li>Best Author Award</li>
              <li>Best Promotion Award</li>
            </ul>
          </div>

          <div className="space-1"></div>

          <Image src={HeroImage} />
        </div>
      </section>

      <section className="products">
      <h1>Products</h1>
      </section>
    </div>
  );
}
