import Head from "next/head";
import { useContext, useEffect } from "react";
import { GlobalContext } from "../../../context/GlobalContext";
import { ButtonLoader } from "../../../components/ButtonLoader";
import { SearchBar } from "../../../components/SearchBar";
import { documentToBlob } from "../../../helpers/fileReader";
import { AdminHeader } from "../../../components/AdminHeader";
import { SideBar } from "../../../components/SideBar";
import { useRouter } from "next/router";
import { deleteProduct } from "../../../services/products";

const Customer = () => {
  const router = useRouter();
  const {
    user: { customers, getAllCustomers },
  } = useContext(GlobalContext);

  // console.log(products);

  useEffect(() => {
    getAllCustomers();
  }, [])

  return (
    <div className="add-product flex">
      <Head>
        <title>UNI-STORE | Add Product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SideBar />

      <div className="main-component">
        <AdminHeader />
        <main>
          <section className="flex col">
            <div className="flex justify-between">
              {/* <button onClick={() => router.push("/admin/products/add-product")} className="btn">Add New</button> */}
              <SearchBar />
            </div>
          </section>
          <div className="space-1"></div>
          <section>
            {/* <h1>Products</h1> */}
            <div className="flex col">
              {customers?.map((items, i) => {
                return (
                  <div className="product-bar flex col" key={i}>
                    <p className="blue">
                      name - {items?.fname} {items?.lname}
                    </p>
                    <p>email - {items?.email}</p>
                    <p>total spend - ${items?.totalSpend}</p>
                  </div>
                );
              })}
            </div>
          </section>
        </main>
      </div>
    </div>
  );
};

export default Customer;
