import Head from "next/head"
import { useContext, useEffect, useState } from "react";
import { GlobalContext } from "../../../../context/GlobalContext";
import { ButtonLoader } from "../../../../components/ButtonLoader";
import { documentToBlob } from "../../../../helpers/fileReader";
import { AdminHeader } from "../../../../components/AdminHeader";
import { SideBar } from "../../../../components/SideBar";
import { useRouter } from "next/router";
import Image from "next/image";

const EditProduct = () => {
    const { order: {
        handleState,
        msg,
        editOrder,
        error,
        loading,
        orders,
    } } = useContext(GlobalContext);

    const [state, setState] = useState({
        data: []
    })

    const { id } = useRouter().query;
    // console.log(id);
    const router = useRouter();

    useEffect(() => {

        const item = orders?.filter(item => item._id === id);
        if (item.length === 0) {
            router.push("/admin/orders");
        } else {
            setState(state => ({
                ...state,
                data: item[0]
            }));
        }
    }, [id])

    return <div className="edit-product flex">
        <Head>
            <title>UNI-STORE | Edit Product</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <SideBar />

        <div className="main-component">
            <AdminHeader />

            <main>
                <section className="flex col">
                    <h1>General</h1>
                    <div className="items-">
                        <div className="input-bar">
                            <small>Name</small>
                            <div className="input">
                                <input defaultValue={state?.data?.fname} placeholder="First Name" onChange={event => handleState("fname", event.target.value)} />
                            </div>
                        </div>
                        <div className="input-bar">
                            <small>Name</small>
                            <div className="input">
                                <input defaultValue={state?.data?.lname} placeholder="Last Name" onChange={event => handleState("lname", event.target.value)} />
                            </div>
                        </div>
                        <div className="input-bar">
                            <small>Status</small>
                            <div className="input">
                                <select defaultValue={state?.data?.status} onChange={event => handleState("status", event.target.value)}>
                                    <option>{state?.data?.status}</option>
                                    <option>On hold</option>
                                    <option>Processing</option>
                                    <option>Complete</option>
                                </select>
                            </div>
                        </div>

                    </div>
                    <div className="space-1"></div>

                    <h1>Billing</h1>
                    <div className="items-">
                        <div className="input-bar">
                            <small>Shipping Address</small>
                            <div className="input">
                                <input defaultValue={state.data?.shipping} placeholder="Shipping Address" type={"text"} onChange={event => handleState("shipping", event.target.value)} />
                            </div>
                        </div>
                        <div className="input-bar">
                            <small>Total Sale ($)</small>
                            <div className="input">
                                <input defaultValue={state.data?.total} placeholder="Total Sale price ($)" type={"number"} onChange={event => handleState("total", event.target.value)} />
                            </div>
                        </div>
                    </div>
                    <div className="space-2"></div>

                    <h1>Products</h1>
                    <div className="items-">
                        <div className="items-1">
                            {state?.data?.products?.items?.map((item, i) => {
                                return <div className="flex" key={i}>
                                    <Image src={item.img} alt="" width={40} height={40}/>
                                    <div className="space-2"></div>
                                    <div className="flex col">
                                        <b>{item.name}</b>
                                        <b className="blue">${item.price}</b>
                                    </div>

                                </div>
                            })}

                        </div>

                        <div className="space-2"></div>
                        <div className={`${error === true ? "red" : "green"}`}>{msg}</div>
                        <div className="space-2"></div>
                        <ButtonLoader value={"Save"} loading={loading} onClick={() => editOrder(id)} />
                        {/* <button onClick={() => saveNewProduct()}>Save</button> */}

                    </div>
                </section>
            </main>
        </div>


    </div>
}

export default EditProduct;